### ISSUE TITLE
Name is misleading

### ISSUE THREAD

**Issue by colintedford** [binarynoir/obsidian-markdown-tags#1]
The name "Markdown Tags" is misleading — they're not Markdown, and they're not tags as Obsidian understands the term. (Or does the plugin register them in Obsidian's tag index? If so, it would be good to say that in the Readme.)

Using words from the Readme, perhaps "Styled labels" would work.

**Comment by kryptonianson** [comment]
Thank you so much for your feedback. You make some excellent points. I will look into this and try and see how I can balance this with my other related extensions that use the same syntax. I have a bit of a problem since I am trying to express it is for markdown and keep it related to tags in other environments. I am sure there is a good solution to cover everything. Thank you I appreciate your feedback.

**Comment by kryptonianson** [comment]
I have addressed your concerns the best I could at the moment by retitling the plugin as "Tags for Markdown" with the description "Enhanced Styled Labels for Obsidian." For additional clarity on why the name keeps tags, I added a link to the related Visual Studio Code extension. I hope you find this satisfactory, and thank you for your valuable input and help in making this product better.
