### ISSUE TITLE
你好，你这插件会导致插入的图片与小组件在阅读模式下显示不出来。关闭插件，图片技能显示

### ISSUE THREAD

**Issue by zhuzhige123** [binarynoir/obsidian-markdown-tags#4]

**Comment by kryptonianson** [comment]
I apologize for the delayed response. Thank you for the report. I will work on a fix and have it soon and let you know when it is released. Should be more than a few days maximum.

**Comment by zhuzhige123** [comment]
In addition, after uninstalling, the attribute official tags may not recognize the tags in the added file content.
I still can't find a way to detect if obsidian-markdown-tags causing residual problems.

(If you don't uninstall, the picture will not be displayed)

**Comment by zhuzhige123** [comment]
@kryptonianson 
In addition, after uninstalling, the attribute official tags may not recognize the tags in the added file content.
I still can't find a way to detect if obsidian-markdown-tags causing residual problems.

(If you don't uninstall, the picture will not be displayed)

**Comment by kryptonianson** [comment]
Still working on these issues. Did not want you to think they are not being addressed. Thank you again for your patience.

**Comment by kryptonianson** [comment]
I am very happy to let you know I have fixed the issue version 1.2.3 and things should work much better. Thank you so much for your patience since this took me some time to fix properly. Also I want to thank you for helping make the extension better by reporting bugs. Please let me know if you have any other issues.

**Comment by zhuzhige123** [comment]
OK，thank you very much!
